const INCREMENT = 'INCREMENT';
const DECREMENT = 'DECREMENT';
const INCREMENT_ASYNC = 'INCREMENT_ASYNC';
const FETCH_TRANSACTION = 'FETCH_TRANSACTION';

export default {
  INCREMENT,
  DECREMENT,
  INCREMENT_ASYNC,
  FETCH_TRANSACTION,
};
